# Generated by Django 4.2.3 on 2023-09-16 16:35

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=book.models.upload_to, verbose_name='Image'),
        ),
    ]
